# name: my-first-website-lse
# region: us-east-1
# frontend:
#   # Specifies the path of your code.
#   path: .
#   # Specifies the folder where the build is located.
#   # This is the folder that will be deployed.
#   publish: dist
#   # Scripts will run in the specified `path` folder.
#   scripts:
#     # The command to build your frontend project. This is custom to your project.
#     # It must to populate the specified `publish` folder with a `index.html` file.
#     deploy:
#       - npm install
#       - npm run build
#   subdomain: gray-welcome-swallow
#   functions:
#     app:
#       handler: app.handler
#       events:
#         - http: ANY /
#         - http: 'ANY {proxy+}'
#       # Configurația proxy-ului pentru ruta /api/location
#       proxy:
#         enabled: true
#         url: http://ip-api.com/json/
# #  backend:
# #     # The root directory of the backend.
# #     path: ./
# #     # Information about the backend's programming language.
# #     language:
# #         # The name of the programming language.
# #         name: js
# #         # The package manager used by the backend.
# #         packageManager: npm
# #     # Scripts are running in the specified `path` directory.
# #     scripts:
# #         # List of scripts to run before deploying the backend.
# #         deploy:
# #             - npm install
# #         # List of scripts to run before deploying the backend.
# #         local:
# #             - npm install
# #     # The cloud provider where the backend is deployed.
# #     cloudProvider: genezio
# # Information about the frontend, including the path, language, and publish directory.
# # It is optional. It can also be an array if there are multiple frontends you want to deploy.
# plugins:
#   - serverless-express
# yamlVersion: 2

name: my-first-website-lse
region: us-east-1

frontend:
  # Specifies the path of your frontend code.
  path: .
  # Specifies the folder where the build is located.
  publish: dist
  # Scripts will run in the specified `path` folder.
  scripts:
    # The command to build your frontend project. This is custom to your project.
    # It must populate the specified `publish` folder with an `index.html` file.
    deploy:
      - npm install
      - npm run build
  subdomain: gray-welcome-swallow

backend:
  # The root directory of the backend.
  path: ./
  # Information about the backend's programming language.
  language:
    # The name of the programming language.
    name: js
    # The package manager used by the backend.
    packageManager: npm
  # Scripts are running in the specified `path` directory.
  scripts:
    # List of scripts to run before deploying the backend.
    deploy:
      - npm install
  functions:
    - name: app
      path: ./ # Path to the file containing the handler function
      entry: app.mjs # The exported function name in the specified file
      handler: app.mjs
      events:
        - http: ANY /
        - http: 'ANY {proxy+}'
      # Configuration for the proxy
      proxy:
        enabled: true
        url: http://ip-api.com/json/

plugins:
  - serverless-express
resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: my-dummy-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
yamlVersion: 2
